### ISSUE TITLE
Error Thread ID not found

### ISSUE THREAD

**Issue by adamsardo** [langchain-ai/open-canvas#134]
Getting an error "Error Thread ID not found" whenever I try generate something. Here's my terminal output.

```
 POST /api/threads 500 in 449ms
Error in proxy
TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleRequest (webpack-internal:///(rsc)/./src/app/api/[..._path]/route.ts:73:21)
    at async /Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038
    at async ek.execute (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)
    at async ek.handle (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)
    at async doRender (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/base-server.js:1357:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/base-server.js:1567:40)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/base-server.js:1487:28)
    at async DevServer.renderPageComponent (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/base-server.js:1911:24)
    at async DevServer.renderToResponseImpl (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/base-server.js:1949:32)
    at async DevServer.pipeImpl (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/base-server.js:916:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/base-server.js:812:17)
    at async /Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/Users/adamsardo/Developer/open-canvas-main/node_modules/next/dist/server/lib/start-server.js:141:13) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:53974
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 53974
  }
}
```

**Comment by girotte-tao** [comment]
Hello, same issue, can you kindly tell me how to solve it?
