### ISSUE TITLE
nextjs bug !

### ISSUE THREAD

**Issue by rcspam** [langchain-ai/open-canvas#148]
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@blocknote/react/dist/blocknote-react.js:309:16)
    at Eo (webpack-internal:///(app-pages-browser)/./node_modules/@blocknote/react/dist/blocknote-react.js:747:4)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@blocknote/react/dist/blocknote-react.js:749:27)
    at (app-pages-browser)/./node_modules/@blocknote/react/dist/blocknote-react.js (http://localhost:3000/_next/static/chunks/app/page.js:10571:1)
    at options.factory (http://localhost:3000/_next/static/chunks/webpack.js:713:31)
    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js:37:33)
    at fn (http://localhost:3000/_next/static/chunks/webpack.js:369:21)
    at eval (webpack-internal:///(app-pages-browser)/./src/components/artifacts/TextRenderer.tsx:11:74)
    at (app-pages-browser)/./src/components/artifacts/TextRenderer.tsx (http://localhost:3000/_next/static/chunks/app/page.js:9794:1)
    at options.factory (http://localhost:3000/_next/static/chunks/webpack.js:713:31)
    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js:37:33)
    at fn (http://localhost:3000/_next/static/chunks/webpack.js:369:21)
    at eval (webpack-internal:///(app-pages-browser)/./src/components/artifacts/ArtifactRenderer.tsx:24:72)
    at (app-pages-browser)/./src/components/artifacts/ArtifactRenderer.tsx (http://localhost:3000/_next/static/chunks/app/page.js:9772:1)
    at options.factory (http://localhost:3000/_next/static/chunks/webpack.js:713:31)
    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js:37:33)
    at fn (http://localhost:3000/_next/static/chunks/webpack.js:369:21)
    at eval (webpack-internal:///(app-pages-browser)/./src/components/Canvas.tsx:6:96)
    at (app-pages-browser)/./src/components/Canvas.tsx (http://localhost:3000/_next/static/chunks/app/page.js:9695:1)
    at options.factory (http://localhost:3000/_next/static/chunks/webpack.js:713:31)
    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js:37:33)
    at fn (http://localhost:3000/_next/static/chunks/webpack.js:369:21)
    at eval (webpack-internal:///(app-pages-browser)/./src/app/page.tsx:6:76)
    at (app-pages-browser)/./src/app/page.tsx (http://localhost:3000/_next/static/chunks/app/page.js:9684:1)
    at options.factory (http://localhost:3000/_next/static/chunks/webpack.js:713:31)
    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js:37:33)
    at fn (http://localhost:3000/_next/static/chunks/webpack.js:369:21)
    at requireAsyncModule (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:67:21)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:104:22)

**Comment by bracesproul** [comment]
Interesting, I haven't seen this before. @rcspam could you please provide steps which I can follow to reproduce it? Ideally a detailed list, and a screen recording. Thank you!

**Comment by rcspam** [comment]
Hi @bracesproul 
i follow instruction to install and start opan-cavas, but and Next.js 14.2.7 plains about an error

**Comment by rcspam** [comment]
Hi @bracesproul ,
After install open-canvas and run it, an error appear about Next.js 14.2.7 see this screenshots:

![Open-Canvas](https://github.com/user-attachments/assets/c9342c88-8899-4ef3-9d56-d8d546f19598)
![Copie d'écran_20241101_113639](https://github.com/user-attachments/assets/b1ee497d-8b08-4f40-b368-e26923d460d0)

So i upgrade nextjs with a `$ yarn add next@latest` as indicated at the link to this page [https://nextjs.org/docs/messages/version-staleness](https://nextjs.org/docs/messages/version-staleness).

then a new 'yarn install' and 'yarn dev' and i have this errors on the landing page of  localhost:3000 .
That's all

**Comment by rcspam** [comment]
@bracesproul 
To be complete if I do not upgrade nextjs (so i let nextjs 14.2.7 version).
Here is the error that I get:
```
$ yarn dev
yarn run v1.22.22
$ next dev
  ▲ Next.js 14.2.7
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1312ms
 ✓ Compiled /src/middleware in 234ms (142 modules)
 ○ Compiling / ...
 ✓ Compiled / in 6.6s (8633 modules)
 GET / 200 in 7713ms
 ✓ Compiled in 1118ms (4274 modules)
 ○ Compiling /api/[..._path] ...
 ✓ Compiled /api/[..._path] in 780ms (4485 modules)
Error in proxy
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleRequest (webpack-internal:///(rsc)/./src/app/api/[..._path]/route.ts:73:21)
    at async /home/rapha/SOURCES/open-canvas/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038
    at async ek.execute (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)
    at async ek.handle (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)
    at async doRender (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1357:42)
    at async cacheEntry.responseCache.get.routeKind (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1567:40)
    at async DevServer.renderToResponseWithComponentsImpl (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1487:28)
    at async DevServer.renderPageComponent (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1911:24)
    at async DevServer.renderToResponseImpl (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1949:32)
    at async DevServer.pipeImpl (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:916:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:812:17)
    at async /home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/home/rapha/SOURCES/open-canvas/node_modules/next/dist/server/lib/start-server.js:141:13) {
  cause: AggregateError [ECONNREFUSED]: 
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}



END ERROR
...
```
This error is repeated multiple time.
Hope help to debug

**Comment by rcspam** [comment]
@bracesproul 
To be complete if I do not upgrade nextjs (so i let nextjs 14.2.7 version).
Here is the error that I get:
```
$ yarn dev
yarn run v1.22.22
$ next dev
  ▲ Next.js 14.2.7
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1312ms
 ✓ Compiled /src/middleware in 234ms (142 modules)
 ○ Compiling / ...
 ✓ Compiled / in 6.6s (8633 modules)
 GET / 200 in 7713ms
 ✓ Compiled in 1118ms (4274 modules)
 ○ Compiling /api/[..._path] ...
 ✓ Compiled /api/[..._path] in 780ms (4485 modules)
Error in proxy
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleRequest (webpack-internal:///(rsc)/./src/app/api/[..._path]/route.ts:73:21)
    at async /home/user/SOURCES/open-canvas/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038
    at async ek.execute (/home/user/SOURCES/open-canvas/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)
    at async ek.handle (/home/user/SOURCES/open-canvas/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)
    at async doRender (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1357:42)
    at async cacheEntry.responseCache.get.routeKind (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1567:40)
    at async DevServer.renderToResponseWithComponentsImpl (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1487:28)
    at async DevServer.renderPageComponent (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1911:24)
    at async DevServer.renderToResponseImpl (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:1949:32)
    at async DevServer.pipeImpl (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:916:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/base-server.js:812:17)
    at async /home/user/SOURCES/open-canvas/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/user/SOURCES/open-canvas/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/home/user/SOURCES/open-canvas/node_modules/next/dist/server/lib/start-server.js:141:13) {
  cause: AggregateError [ECONNREFUSED]: 
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}



END ERROR
...
```
This error is repeated multiple time.
Hope help to debug

**Comment by rcspam** [comment]
Sorry @bracesproul ,
I guess you want to say that i have to fill the LANGGRAPH_API_URL environment variable in .env. But i don't find how to setup this ! Tthis video doesn't explain how to create a langgraph cloud url instance, i am on a linux system and langgraph studio is only for Mac. 
Yet sorry i'm trying just to test open-canva and my skill is limited. Can you tell me howto proceed

**Comment by KlotzJesse** [comment]
> Interesting, I haven't seen this before. @rcspam could you please provide steps which I can follow to reproduce it? Ideally a detailed list, and a screen recording. Thank you!

happens when having a react version mismatch, e.g. using nextjs 15 with react 19 rc, because we currently unnecessary bundle react/jsx-runtime here, gonna make a pr for this
