### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by Pcyslist** [langchain-ai/open-canvas#194]
Traceback is  shown below:
2024-11-11T10:59:36.677463Z [info     ] Started server process [1]     [uvicorn.error] api_revision=2f1052b api_variant=local color_message=Started server process [%d]
[langgraph-api]      | 2024-11-11T10:59:36.677662Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=2f1052b api_variant=local
[langgraph-api]      | 2024-11-11T10:59:36.677997Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=2f1052b api_variant=local
[langgraph-api]      | 2024-11-11T10:59:37.022707Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 " [httpx] api_revision=2f1052b api_variant=local
2024-11-11T10:59:37.074102Z [error    ] Traceback (most recent call last):
[langgraph-api]      |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
[langgraph-api]      |     async with self.lifespan_context(app) as maybe_state:
[langgraph-api]      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[langgraph-api]      |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
[langgraph-api]      |     return await anext(self.gen)
[langgraph-api]      |            ^^^^^^^^^^^^^^^^^^^^^
[langgraph-api]      |   File "/api/langgraph_api/lifespan.py", line 29, in lifespan
[langgraph-api]      |   File "/usr/local/lib/python3.12/site-packages/langgraph_storage/database.py", line 115, in start_pool
[langgraph-api]      |     await migrate()
[langgraph-api]      |   File "/usr/local/lib/python3.12/site-packages/langgraph_storage/database.py", line 97, in migrate
[langgraph-api]      |     if version <= current_version:
[langgraph-api]      |        ^^^^^^^^^^^^^^^^^^^^^^^^^^
[langgraph-api]      | TypeError: '<=' not supported between instances of 'int' and 'str'
[langgraph-api]      |  [uvicorn.error] api_revision=2f1052b api_variant=local
[langgraph-api]      | 2024-11-11T10:59:37.074303Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=2f1052b api_variant=local
exit code: 3

**Comment by bracesproul** [comment]
How can I reproduce this error?
