### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by 18600709862** [langchain-ai/open-canvas#34]
steps

1、langgraph up
result:
Ready!       
- API: http://localhost:8123
- Docs: http://localhost:8123/docs
- Debugger: https://smith.langchain.com/studio/?baseUrl=http://127.0.0.1:8123

2、vim .env add
LANGCHAIN_API_KEY
LANGGRAPH_API_URL=http://localhost:8123
All settings are filled in.

3、yarn dev
result：
yarn run v1.22.22
$ next dev
  ▲ Next.js 14.2.7
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 2.7s
 ○ Compiling / ...
 ✓ Compiled / in 8.6s (4192 modules)
 GET / 200 in 11063ms
 ✓ Compiled in 2.3s (2101 modules)
 ○ Compiling /api/[..._path] ...
 ✓ Compiled /api/[..._path] in 1011ms (2121 modules)
 ✓ Compiled (2166 modules)
 GET /favicon.ico 200 in 1916ms
 POST /api/store/get 200 in 1801ms
 POST /api/threads 200 in 1819ms
 POST /api/threads 200 in 1821ms

4、open browser and start interacting
input :Search for the best restaurant
display  A  ,Then, nothing is displayed
log:
POST /api/threads/80ca6f6c-a4b5-4a56-b5fa-b33da7041bb6/runs/stream 200 in 629ms
 ○ Compiling /api/runs/share ...
 ✓ Compiled /api/runs/share in 1011ms (2248 modules)
Attempt 1 failed. Retrying in 5 seconds...
 POST /api/runs/share 200 in 7920ms

Is there something wrong with the settings?

**Comment by bracesproul** [comment]
What's the error you're experiencing? @18600709862

**Comment by losexing** [comment]
POST /api/assistants 500 in 10056ms
Error in proxy
TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleRequest (webpack-internal:///(rsc)/./src/app/api/[..._path]/route.ts:42:21)
    at async E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55038
    at async ek.execute (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:45808)
    at async ek.handle (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:56292)
    at async doRender (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1357:42)
    at async cacheEntry.responseCache.get.routeKind (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1567:40)
    at async DevServer.renderToResponseWithComponentsImpl (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1487:28)
    at async DevServer.renderPageComponent (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1911:24)
    at async DevServer.renderToResponseImpl (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1949:32)
    at async DevServer.pipeImpl (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:916:25)
    at async NextNodeServer.handleCatchallRenderRequest (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:812:17)
    at async E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (E:\workspace\open-canvas\node_modules\.pnpm\next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\start-server.js:141:13) {
  [cause]: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
      at node:internal/deps/undici/undici:6587:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6617:37)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

**Comment by 18600709862** [comment]
@bracesproul
in .env  set
OPENAI_API_KEY=sk-xxx
OPENAI_BASE_URL=http://localhost:1337/v1
why connection error  
local llm not use,  so  as ollama

**Comment by bracesproul** [comment]
@18600709862 / @losexing  You need to have the API running as well. Do you have LangGraph studio installed and is the project running? See this comment with those instructions https://github.com/langchain-ai/open-canvas/issues/44#issuecomment-2420503163

**Comment by chenjiawei30** [comment]
@18600709862  The same problem :) Have you solved this issue?
